on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy_job:
    name: deploy to gh-pages
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get build dependencies
        run: sudo apt-get update && sudo apt-get install plantuml texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-full ttf-mscorefonts-installer && sudo fc-cache -f
      - name: Compile LaTeX document
        run: |
          cd docs
          make -B deploy
          cd ..
      - name: Cleanup
        run: cp ./docs/.gitignore.deploy .docs/.gitignore
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
